// Auto-generated - DO NOT EDIT
// Generated by: pnpm blog:build

import type { BlogPostMeta, BlogPost } from '../../types/blog'

import { whoamiInChrist } from './whoami-in-christ'
import { writtenTestimony } from './written-testimony'

// All blog posts with full content
export const blogPosts: Record<string, BlogPost> = {
  'whoami-in-christ': whoamiInChrist,
  'written-testimony': writtenTestimony,
}

// Blog posts metadata only (for listing pages)
export const blogPostsMeta: BlogPostMeta[] = [
  {
    title: "Whoami in Christ",
    slug: "whoami-in-christ",
    excerpt: "Learn how to share your Christian testimony in 15 minutes or less. This is designed for new or experienced believers to share the life-changing power of your faith.",
    featuredImage: "/images/blog/whoami-in-christ.png",
    category: "Discipleship",
    publishDate: "2026-01-16",
    author: "Jones",
    tags: ["discipleship","faith","declaration","existence"],
    subtitle: "Scriptural declarations to make over yourself: I Am Significant in Christ.",
  },
  {
    title: "Written Testimony",
    slug: "written-testimony",
    excerpt: "Learn how to share your Christian testimony in 15 minutes or less. This is designed for new or experienced believers to share the life-changing power of your faith.",
    featuredImage: "/images/blog/20minute-testimony.png",
    category: "Testimony",
    publishDate: "2024-01-15",
    author: "JH Outback Team",
    tags: ["testimony","faith","guide"],
    subtitle: "HOW TO PREPARE A 20-minute TESTIMONY - GENERAL OUTLINE",
  },
]

// Get a single blog post by slug
export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts[slug]
}

// Get all categories
export function getAllCategories(): string[] {
  const categories = new Set(blogPostsMeta.map((post) => post.category))
  return Array.from(categories).sort()
}

// Get all tags
export function getAllTags(): string[] {
  const tags = new Set(blogPostsMeta.flatMap((post) => post.tags))
  return Array.from(tags).sort()
}

export default blogPosts
