// Auto-generated - DO NOT EDIT
// Generated by: pnpm blog:build
// Source: blog-content/whoami-in-christ.md

import type { BlogPost } from '../../types/blog'

export const whoamiInChrist: BlogPost = {
  title: "Whoami in Christ",
  slug: "whoami-in-christ",
  excerpt: "Learn how to share your Christian testimony in 15 minutes or less. This is designed for new or experienced believers to share the life-changing power of your faith.",
  featuredImage: "/images/blog/whoami-in-christ.png",
  category: "Discipleship",
  publishDate: "2026-01-16",
  author: "Jones",
  tags: ["discipleship","faith","declaration","existence"],
  subtitle: "Scriptural declarations to make over yourself: I Am Significant in Christ.",
  content: `<h2 class="text-2xl font-bold text-primary mt-10 mb-4">Daily Declaration: Who I Am in Christ</h2>

<p class="text-gray-600 my-4">_A practice of Scripture reading, confession, and reverent reflection (NIV)_</p>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">“Do your best to present yourself to God as one approved,</blockquote>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">a worker who does not need to be ashamed</blockquote>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">and who correctly handles the word of truth.”</blockquote>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">— 2 Timothy 2:15 (NIV)</blockquote>

<p class="text-gray-600 my-4">This daily declaration is <strong>not a replacement for Scripture</strong>.</p>
<p class="text-gray-600 my-4">It is a <strong>response to Scripture</strong>.</p>

<p class="text-gray-600 my-4">These words carry no power on their own unless they are rooted in a <strong>living, growing understanding of the Word of God</strong>. Confidence in declaring truth comes only from first <strong>knowing</strong>, <strong>reading</strong>, and <strong>rightly understanding</strong> what God has actually said—within its original context and intent.</p>

<p class="text-gray-600 my-4">If we do not read the Scriptures for ourselves, reflect deeply on their meaning, and allow them to shape our character, then repeating these declarations becomes empty repetition. But when these truths are drawn from Scripture we have personally engaged with, they become anchors for the soul.</p>

<p class="text-gray-600 my-4">Before you declare these truths, <strong>read the original passages</strong>. Sit with them. Ask questions. Pray over them. Let God speak through His Word.</p>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">“Blessed is the one who delights in the law of the Lord,</blockquote>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">and who meditates on his law day and night.”</blockquote>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">— Psalm 1:2 (NIV)</blockquote>

<p class="text-gray-600 my-4">All Scripture references are from the <strong>New International Version (NIV)</strong> and linked via <a href="https://www.bible.com/bible/111" class="text-accent hover:underline">Bible.com</a>.</p>

<p class="text-gray-600 my-4">---</p>

<h3 class="text-xl font-bold text-primary mt-8 mb-4">Part 1: I Am Significant in Christ</h3>

<p class="text-gray-600 my-4">My significance does not come from status, position, gifting, or visibility.</p>
<p class="text-gray-600 my-4">It comes from being <strong>in Christ</strong>.</p>

<p class="text-gray-600 my-4">Every believer—no matter their role—is a vital part of the body. How I think, speak, and act matters because I am not isolated; I am connected. When I live in truth, the body is strengthened. When I walk carelessly, the body is affected.</p>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">“Now you are the body of Christ, and each one of you is a part of it.”</blockquote>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">— 1 Corinthians 12:27 (NIV)</blockquote>

<h4 class="text-lg font-bold text-primary mt-6 mb-3">Scriptural Declarations</h4>

<p class="text-gray-600 my-4">_(Read the full passages before declaring them.)_</p>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am the salt of the earth</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/MAT.5.13" class="text-accent hover:underline">Matthew 5:13 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am the light of the world</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/MAT.5.14" class="text-accent hover:underline">Matthew 5:14 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am God’s child</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/JHN.1.12" class="text-accent hover:underline">John 1:12 (NIV)</a>
<p class="text-gray-600 my-4">_(See also <a href="https://www.bible.com/bible/111/1JN.3.1-3" class="text-accent hover:underline">1 John 3:1–3 (NIV)</a>)_</p>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am a branch of the true vine, a channel of Christ’s life</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/JHN.15.1-5" class="text-accent hover:underline">John 15:1, 5 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I have been chosen and appointed to bear fruit</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/JHN.15.16" class="text-accent hover:underline">John 15:16 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am a personal witness of Christ</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/ACT.1.8" class="text-accent hover:underline">Acts 1:8 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am God’s temple</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/1CO.3.16" class="text-accent hover:underline">1 Corinthians 3:16 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am a member of Christ’s body</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/1CO.12.27" class="text-accent hover:underline">1 Corinthians 12:27 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am a minister of reconciliation for God</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/2CO.5.17-18" class="text-accent hover:underline">2 Corinthians 5:17–18 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am God’s co-worker</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/2CO.6.1" class="text-accent hover:underline">2 Corinthians 6:1 (NIV)</a>
<p class="text-gray-600 my-4">_(See also <a href="https://www.bible.com/bible/111/1CO.3.9" class="text-accent hover:underline">1 Corinthians 3:9 (NIV)</a>)_</p>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am a saint</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/EPH.1.1" class="text-accent hover:underline">Ephesians 1:1 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I have been raised up and seated with Christ</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/EPH.2.6" class="text-accent hover:underline">Ephesians 2:6 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am God’s workmanship</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/EPH.2.10" class="text-accent hover:underline">Ephesians 2:10 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am a citizen of heaven</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/PHP.3.20" class="text-accent hover:underline">Philippians 3:20 (NIV)</a>

<h4 class="text-lg font-bold text-primary mt-6 mb-3">Reflection & Application</h4>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span>Read each passage in its <strong>full context</strong>.</span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span>Rewrite each declaration of <strong>significance</strong> in your own words.</span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span>Reflect deeply:</span></li>
</ul>  - _What responsibility comes with this truth?_
<p class="text-gray-600 my-4">- _How does my thinking or behavior affect the body of Christ?_</p>
<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span>Pray not just for understanding—but for transformation.</span></li>
</ul>
<p class="text-gray-600 my-4">---</p>

<h3 class="text-xl font-bold text-primary mt-8 mb-4">Part 2: I Am Accepted in Christ</h3>

<p class="text-gray-600 my-4">My acceptance is not based on performance, perfection, or comparison.</p>
<p class="text-gray-600 my-4">It is grounded in the finished work of Christ.</p>

<p class="text-gray-600 my-4">Understanding this truth changes how I approach God—and how I treat others.</p>
<p class="text-gray-600 my-4">When I know I am accepted, I no longer need to strive, hide, or compete.</p>
<p class="text-gray-600 my-4">I can walk humbly, confidently, and in love.</p>

<h4 class="text-lg font-bold text-primary mt-6 mb-3">Scriptural Declarations</h4>

<p class="text-gray-600 my-4">_(Read slowly. Reflect deeply. Do not rush.)_</p>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am Jesus’ friend</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/JHN.15.15" class="text-accent hover:underline">John 15:15 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I have been justified</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/ROM.5.1" class="text-accent hover:underline">Romans 5:1 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am joined to the Lord and one in spirit with Him</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/1CO.6.17" class="text-accent hover:underline">1 Corinthians 6:17 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I have been bought with a price; I belong to God</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/1CO.6.20" class="text-accent hover:underline">1 Corinthians 6:20 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am a member of Christ’s body</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/1CO.12.27" class="text-accent hover:underline">1 Corinthians 12:27 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I have been made righteous</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/2CO.5.21" class="text-accent hover:underline">2 Corinthians 5:21 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I have been adopted as God’s child</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/EPH.1.5" class="text-accent hover:underline">Ephesians 1:5 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I have direct access to God through the Holy Spirit</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/EPH.2.18" class="text-accent hover:underline">Ephesians 2:18 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am a member of God’s household</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/EPH.2.19" class="text-accent hover:underline">Ephesians 2:19 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I can approach God with boldness and confidence</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/EPH.3.12" class="text-accent hover:underline">Ephesians 3:12 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I have been redeemed and forgiven of all my sins</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/COL.1.14" class="text-accent hover:underline">Colossians 1:14 (NIV)</a>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span><strong>I am complete in Christ</strong></span></li>
</ul>  <a href="https://www.bible.com/bible/111/COL.2.10" class="text-accent hover:underline">Colossians 2:10 (NIV)</a>

<h4 class="text-lg font-bold text-primary mt-6 mb-3">Reflection & Application</h4>

<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span>Rewrite each declaration of <strong>acceptance</strong> in your own words.</span></li>
<li class="flex items-start gap-2"><span class="text-accent">•</span><span>Ask yourself:</span></li>
</ul>  - _Do I truly believe this—or am I still striving to earn what God has already given?_
<ul class="space-y-2 text-gray-600 my-4"><li class="flex items-start gap-2"><span class="text-accent">•</span><span>Let Scripture define your identity, not emotions or circumstances.</span></li>
</ul>
<p class="text-gray-600 my-4">---</p>

<h3 class="text-xl font-bold text-primary mt-8 mb-4">A Call to Deep Reflection</h3>

<p class="text-gray-600 my-4">These declarations are <strong>alive</strong> only when they are grounded in Scripture,</p>
<p class="text-gray-600 my-4">understood in context, and lived out in obedience.</p>

<p class="text-gray-600 my-4">You are not insignificant.</p>
<p class="text-gray-600 my-4">You are not unseen.</p>
<p class="text-gray-600 my-4">You are not separate from the body.</p>

<p class="text-gray-600 my-4">You matter because <strong>Christ has joined you to Himself</strong>,</p>
<p class="text-gray-600 my-4">and through you, He works in the world.</p>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">“Let the word of Christ dwell in you richly…”</blockquote>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">— Colossians 3:16 (NIV)</blockquote>

<p class="text-gray-600 my-4">---</p>

<h3 class="text-xl font-bold text-primary mt-8 mb-4">Closing Prayer</h3>

<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">\*Father,</blockquote>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">Teach me to love Your Word,</blockquote>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">to read it carefully, understand it rightly,</blockquote>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">and live it faithfully.</blockquote>
<p class="text-gray-600 my-4">></p>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">Shape my character through truth.</blockquote>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">Guard my heart from shallow belief.</blockquote>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">Let Your Word dwell in me richly</blockquote>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">so that my life strengthens the body of Christ.</blockquote>
<p class="text-gray-600 my-4">></p>
<blockquote class="border-l-4 border-accent pl-4 my-6 italic text-gray-600">In Jesus’ name, Amen.\*</blockquote>

<p class="text-gray-600 my-4">---</p>

<strong>Suggested Practice:</strong>
<p class="text-gray-600 my-4">Read the passage first.</p>
<p class="text-gray-600 my-4">Reflect deeply.</p>
<p class="text-gray-600 my-4">Declare thoughtfully.</p>
<p class="text-gray-600 my-4">Live faithfully.</p>`,
}

export default whoamiInChrist
